### ISSUE TITLE
Issues with the MP-DCCP manual for existing builds

### ISSUE THREAD

**Issue by mrconter1** [telekom/mp-dccp#17]
Hi!

I am trying to set up a system using [this](https://multipath-dccp.org/builds.html) guide. There are three things I want to address. Firstly, I think that the network configuration for the client should be revised as following:

```diff
<interface type='network'>
 <source network='net2'/>
 <model type='rtl8139'/>
- <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'//>
+ <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
</interface>
<interface type='network'>
 <source network='net1'/>
 <model type='rtl8139'/>
- <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>/>
+ <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
</interface>
```

Secondly, I get this error when I try to edit the network configuration for the client:
```
error: XML error: Attempted double use of PCI Address 0000:00:08.0
```
How can I solve this problem? Is is possible for me to choose any other slot?

**Comment by NathalieRM** [comment]
Hi,

Thanks for your feedback, you are right, the client configuration section will be corrected accordingly. Regarding your question, yes, the solution is to choose another slot, however, the network configuration under /etc/network/interfaces has to be updated as well. The PCI slots match with the device names. i.e. slots 8 and 9 with interfaces ens8 and ens9. If a higher slot address is selected instead slot='0x08, for example slot='0x0a', the interface name will be ens10 and that name has to be updated in the /etc/network/interfaces file.

Please, also keep in mind that the existing builds contain a quite outdated version of the MP-DCCP module, and therefore can only be used for testing with the iperf version included inside the builds. Updated builds will be published in the next weeks.

**Comment by mrconter1** [comment]
Thanks!
