### ISSUE TITLE
MP negotiated despite MP-DCCP disabled on interface

### ISSUE THREAD

**Issue by markusa** [telekom/mp-dccp#29]
If MP-DCCP is disabled on an interface, incoming MP_CAPABLE and MP_KEY are negotiated anyway. This should not be the case.

In the scenario where MP_JOIN is received, the request is rejected with a RESET. This is an expected result.

**Comment by LeonardWalter** [comment]
Ok I pushed a fix for this. 
But what about a scenario where we don't want one of our interfaces to be used with MP-DCCP when we are the client/initiator of the connection -
and at the same time, it would be OK for incoming requests to use MP-DCCP on this interface?
Does it make sense to distinguish here?

**Comment by markusa** [comment]
1. Thanks
2. Can you clearer describe the scenario you have in mind for which you consider case distinction. Didn't get it so far.

**Comment by LeonardWalter** [comment]
1. My device (A) should not use the cellular interface for bundling when I make requests from it. So I remove the MPDCCP flag from the cellular interface.
2.  I download a file from device (B). I only use my wifi interface, but device B (which also supports MPDCCP) might advertise additional interfaces. And I can make connections from WiFi to them.
3. I also host some services on my device, and they can only be reached through the cellular interface (where MP-DCCP is disabled).
4. Now some other device (B) also has multiple interfaces and might want to access data from my device (A).

5. Device (B) sends MPDCCP capable request to device (A)
6. Device (A) drops the MP-Capable and responds with a regular DCCP response
7. Device (B) now can not join the connection with its other Interfaces

8. If we would distinguish here, we could allow multiple incoming subflows on this interface - but not use this interface for outgoing requests.

**Comment by NathalieRM** [comment]
If MP-DCCP is disabled in an interface, both, outgoing and incoming connections should fallback to single path DCCP. The scenario where an address Id advertised over an already established single path DCCP connection, should not occur.

**Comment by NathalieRM** [comment]
Solved in PR #30
