### ISSUE TITLE
Initiate MP-DCCP connection using the Ip address bound to the socket

### ISSUE THREAD

**Issue by LeonardWalter** [telekom/mp-dccp#5]
Currently, the MPDCCP path manager creates the first subflow on whatever address is at first place in plocal_addr_list.
In this state MPDCCP does not:
- handle if it is bound to a socket
- follow routing rules, e.g. use the default address/interface to initiate the connection

**Comment by DanielP2D** [comment]
Hi, Can anyone please tell me what are the types of path_managers supported in kernel 5.10.136?
